# gameplay
server_name = "playtest"
tick_rate = 30
max_players = 10 

# atmos
atmos_enabled = true 

# net
port = 2197 
address = "127.0.0.1"
make_local_admin = true

# Round settings
lobby_timer = 3
lobby_enabled = true
round_end_timer = 60

map_name = "empty_map"

gamemode = "extended"
